-- MySQL Script generated by MySQL Workbench
-- 10/22/19 15:24:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cpa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cpa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cpa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cpa` ;

-- -----------------------------------------------------
-- Table `cpa`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`Usuario` (
  `usuario` VARCHAR(45) NOT NULL COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `sobrenome` VARCHAR(200) NOT NULL COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`usuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`TipoResposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`TipoResposta` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`TipoPergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`TipoPergunta` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `TipoResposta_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `TipoResposta_id`)  COMMENT '',
  INDEX `fk_TipoPergunta_TipoResposta1_idx` (`TipoResposta_id` ASC)  COMMENT '',
  CONSTRAINT `fk_TipoPergunta_TipoResposta1`
    FOREIGN KEY (`TipoResposta_id`)
    REFERENCES `cpa`.`TipoResposta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`TipoQuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`TipoQuestionario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `descricao` VARCHAR(300) NULL COMMENT '',
  `TipoPergunta_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `TipoPergunta_id`)  COMMENT '',
  INDEX `fk_TipoQuestionario_TipoPergunta1_idx` (`TipoPergunta_id` ASC)  COMMENT '',
  CONSTRAINT `fk_TipoQuestionario_TipoPergunta1`
    FOREIGN KEY (`TipoPergunta_id`)
    REFERENCES `cpa`.`TipoPergunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`Questionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`Questionario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `descricao` VARCHAR(300) NULL COMMENT '',
  `Usuario_usuario` VARCHAR(45) NOT NULL COMMENT '',
  `TipoQuestionario_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Usuario_usuario`, `TipoQuestionario_id`)  COMMENT '',
  INDEX `fk_Questionario_Usuario_idx` (`Usuario_usuario` ASC)  COMMENT '',
  INDEX `fk_Questionario_TipoQuestionario1_idx` (`TipoQuestionario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Questionario_Usuario`
    FOREIGN KEY (`Usuario_usuario`)
    REFERENCES `cpa`.`Usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questionario_TipoQuestionario1`
    FOREIGN KEY (`TipoQuestionario_id`)
    REFERENCES `cpa`.`TipoQuestionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`Pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`Pergunta` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pergunta` VARCHAR(300) NOT NULL COMMENT '',
  `TipoPergunta_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `TipoPergunta_id`)  COMMENT '',
  INDEX `fk_Pergunta_TipoPergunta1_idx` (`TipoPergunta_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Pergunta_TipoPergunta1`
    FOREIGN KEY (`TipoPergunta_id`)
    REFERENCES `cpa`.`TipoPergunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`Resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`Resposta` (
  `id` INT NOT NULL COMMENT '',
  `resposta` VARCHAR(45) NOT NULL COMMENT '',
  `TipoResposta_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `TipoResposta_id`)  COMMENT '',
  INDEX `fk_Resposta_TipoResposta1_idx` (`TipoResposta_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Resposta_TipoResposta1`
    FOREIGN KEY (`TipoResposta_id`)
    REFERENCES `cpa`.`TipoResposta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`Campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`Campus` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `campus` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`Curso` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `curso` VARCHAR(150) NOT NULL COMMENT '',
  `Campus_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Campus_id`)  COMMENT '',
  INDEX `fk_Curso_Campus1_idx` (`Campus_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Curso_Campus1`
    FOREIGN KEY (`Campus_id`)
    REFERENCES `cpa`.`Campus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`Disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `disciplina` VARCHAR(300) NOT NULL COMMENT '',
  `Curso_id` INT NOT NULL COMMENT '',
  `periodo` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Curso_id`)  COMMENT '',
  INDEX `fk_Disciplina_Curso1_idx` (`Curso_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Disciplina_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `cpa`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`RespostaQuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`RespostaQuestionario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `alternativaMarcada` VARCHAR(1) NOT NULL COMMENT '',
  `semestreMarcado` VARCHAR(6) NOT NULL COMMENT '',
  `Questionario_id` INT NOT NULL COMMENT '',
  `Campus_id` INT NOT NULL COMMENT '',
  `Disciplina_id` INT NOT NULL COMMENT '',
  `Curso_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Questionario_id`, `Campus_id`, `Disciplina_id`, `Curso_id`)  COMMENT '',
  INDEX `fk_RespostaQuestionario_Questionario1_idx` (`Questionario_id` ASC)  COMMENT '',
  INDEX `fk_RespostaQuestionario_Campus1_idx` (`Campus_id` ASC)  COMMENT '',
  INDEX `fk_RespostaQuestionario_Disciplina1_idx` (`Disciplina_id` ASC)  COMMENT '',
  INDEX `fk_RespostaQuestionario_Curso1_idx` (`Curso_id` ASC)  COMMENT '',
  CONSTRAINT `fk_RespostaQuestionario_Questionario1`
    FOREIGN KEY (`Questionario_id`)
    REFERENCES `cpa`.`Questionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RespostaQuestionario_Campus1`
    FOREIGN KEY (`Campus_id`)
    REFERENCES `cpa`.`Campus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RespostaQuestionario_Disciplina1`
    FOREIGN KEY (`Disciplina_id`)
    REFERENCES `cpa`.`Disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RespostaQuestionario_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `cpa`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpa`.`ListaRespostaMarcada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpa`.`ListaRespostaMarcada` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `RespostaQuestionario_id` INT NOT NULL COMMENT '',
  `Resposta_id` INT NOT NULL COMMENT '',
  `Pergunta_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `RespostaQuestionario_id`, `Resposta_id`, `Pergunta_id`)  COMMENT '',
  INDEX `fk_ListaRespostaMarcada_RespostaQuestionario1_idx` (`RespostaQuestionario_id` ASC)  COMMENT '',
  INDEX `fk_ListaRespostaMarcada_Resposta1_idx` (`Resposta_id` ASC)  COMMENT '',
  INDEX `fk_ListaRespostaMarcada_Pergunta1_idx` (`Pergunta_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ListaRespostaMarcada_RespostaQuestionario1`
    FOREIGN KEY (`RespostaQuestionario_id`)
    REFERENCES `cpa`.`RespostaQuestionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ListaRespostaMarcada_Resposta1`
    FOREIGN KEY (`Resposta_id`)
    REFERENCES `cpa`.`Resposta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ListaRespostaMarcada_Pergunta1`
    FOREIGN KEY (`Pergunta_id`)
    REFERENCES `cpa`.`Pergunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
